# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cutos < Formula
  desc "The easiest way to write OpenAPI 3 documentation from copying curl"
  homepage "https://github.com/cjp2600/cutos/"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cjp2600/cutos/releases/download/v0.0.7/cutos_Darwin_arm64.tar.gz"
      sha256 "17dfb5c2c512c34036664bba783f463d69a3a3cef5552d10714845e7bb2f113f"

      def install
        bin.install "cutos"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cjp2600/cutos/releases/download/v0.0.7/cutos_Darwin_x86_64.tar.gz"
      sha256 "abb230cd09aa9e795c2697d81d7f2521dac92583df5b08e82648e0101dbcb4d5"

      def install
        bin.install "cutos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cjp2600/cutos/releases/download/v0.0.7/cutos_Linux_arm64.tar.gz"
      sha256 "e080f2262b5c5d480cd35c7f58ef4ff1c8c8a071f4958c7747ba42d927898a4e"

      def install
        bin.install "cutos"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cjp2600/cutos/releases/download/v0.0.7/cutos_Linux_x86_64.tar.gz"
      sha256 "992d28382757296941b03bd2ab4cbb63c537ae0e8753d741e5d0801ce768df45"

      def install
        bin.install "cutos"
      end
    end
  end

  test do
    system "cutos version"
  end
end
