# This file was generated by GoReleaser. DO NOT EDIT.
class Cutos < Formula
  desc "Cutos curl to swagger"
  homepage "https://github.com/cjp2600"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cjp2600/cutos/releases/download/v0.0.4/cutos_Darwin_x86_64.tar.gz"
    sha256 "8ad000ec0e3b55389aef797c428632b01c4634553687cd2843b6ad0851a7c7a5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cjp2600/cutos/releases/download/v0.0.4/cutos_Linux_arm64.tar.gz"
      sha256 "0057382b401574ad7a02c5dfaeffd9b20334d19656484f265fc5f1ccbe42aeaa"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cjp2600/cutos/releases/download/v0.0.4/cutos_Linux_arm64.tar.gz"
        sha256 "0057382b401574ad7a02c5dfaeffd9b20334d19656484f265fc5f1ccbe42aeaa"
      else
      end
    end
  end

  def install
    bin.install "cutos"
  end

  test do
    system "cutos version"
  end
end
